import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Supersayan WebMCP Security',
  description: 'Terms of Service for Supersayan WebMCP Security and VLABS, LLC.',
};

const EFFECTIVE_DATE = 'July 1, 2026';
const COMPANY = 'VLABS, LLC';
const PRODUCT = 'Supersayan WebMCP Security';
const CONTACT_EMAIL = 'legal@vril.li';
const SITE_URL = 'https://webmcp.vril.dev';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Nav bar */}
      <div className="border-b border-white/10 flex items-center justify-between px-6 py-4 max-w-5xl mx-auto w-full">
        <Link href="/" className="text-sm text-white/60 hover:text-white transition-colors">
          &larr; Back to {PRODUCT}
        </Link>
        <a href="https://vril.li" target="_blank" rel="noopener noreferrer" aria-label="VRIL LABS">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/vril-labs-logo.svg" alt="VRIL LABS" className="h-6 w-auto opacity-70 hover:opacity-100 transition-opacity" />
        </a>
      </div>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2 text-white">Terms of Service</h1>
        <p className="text-white/50 text-sm mb-10">Effective Date: {EFFECTIVE_DATE} &mdash; Last Updated: {EFFECTIVE_DATE}</p>

        <Section title="1. Agreement to Terms">
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you and {COMPANY},
            a Delaware limited liability company (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;),
            governing your access to and use of {PRODUCT} and all related services, tools, content, and functionality
            available at <a href={SITE_URL} className="text-[#00FFC8] hover:underline">{SITE_URL}</a> (collectively, the &ldquo;Service&rdquo;).
          </p>
          <p className="mt-3">
            By accessing or using the Service, you represent that you are at least 18 years of age, have the legal capacity to enter
            into binding contracts, and agree to be bound by these Terms and our{' '}
            <Link href="/privacy" className="text-[#00FFC8] hover:underline">Privacy Policy</Link>, incorporated herein by reference.
            If you do not agree to these Terms, you must immediately discontinue use of the Service.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            {PRODUCT} is a browser-based security research and intelligence platform designed to detect, analyze, and report on
            WebMCP protocol usage, AI agent activity, headless browser automation, and related covert network behavior. The Service
            is provided solely for lawful security research, educational, and informational purposes.
          </p>
          <p className="mt-3">
            All detection results, threat scores, CVE data, and analysis outputs generated by the Service are provided for
            informational and research purposes only. They do not constitute legal advice, professional security consulting,
            or a guarantee of security.
          </p>
        </Section>

        <Section title="3. Acceptable Use">
          <p className="mb-3">You agree to use the Service only for lawful purposes. You expressly agree not to:</p>
          <ul className="list-disc list-inside space-y-2 text-white/70">
            <li>Use the Service to conduct unauthorized access, penetration testing, or any offensive security operation against systems or networks you do not own or have explicit written permission to test.</li>
            <li>Use the Service to circumvent, reverse-engineer, or undermine security mechanisms of third-party systems.</li>
            <li>Use the Service in any manner that violates the Computer Fraud and Abuse Act (18 U.S.C. § 1030), the Electronic Communications Privacy Act, the California Computer Data Access and Fraud Act, or any other applicable federal, state, or local law.</li>
            <li>Distribute, sublicense, sell, resell, or otherwise commercialize the Service or its outputs without our express written consent.</li>
            <li>Attempt to probe, scan, or test the vulnerability of the Service or any system or network associated with the Service.</li>
            <li>Introduce viruses, worms, Trojan horses, or other malicious or harmful code into the Service.</li>
            <li>Use automated scraping, crawling, or data extraction tools against the Service without our prior written authorization.</li>
            <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity.</li>
          </ul>
          <p className="mt-3">
            We reserve the right to terminate or suspend your access to the Service immediately, without prior notice or liability,
            for any breach of this Section.
          </p>
        </Section>

        <Section title="4. Intellectual Property">
          <p>
            The Service and its original content, features, functionality, source code, algorithms, trademarks, and design are and
            remain the exclusive property of {COMPANY} and its licensors, protected by copyright, trademark, trade secret, and
            other intellectual property laws of the United States and Delaware. Nothing in these Terms transfers any intellectual
            property rights to you.
          </p>
          <p className="mt-3">
            Portions of {PRODUCT} may be made available as open-source software under the MIT License. Your use of any such
            open-source components is governed solely by the applicable open-source license, not these Terms.
          </p>
        </Section>

        <Section title="5. Disclaimer of Warranties">
          <p className="uppercase font-semibold text-white mb-2">
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; WITHOUT WARRANTY OF ANY KIND.
          </p>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY.toUpperCase()} EXPRESSLY DISCLAIMS ALL WARRANTIES,
            WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE
            SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT
            WARRANT THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY DETECTION RESULTS, THREAT SCORES, OR OTHER OUTPUTS
            GENERATED BY THE SERVICE.
          </p>
          <p className="mt-3">
            THE SERVICE IS INTENDED FOR SECURITY RESEARCH AND INFORMATIONAL PURPOSES ONLY. ANY RELIANCE YOU PLACE ON INFORMATION
            PROVIDED BY THE SERVICE IS STRICTLY AT YOUR OWN RISK.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p className="uppercase font-semibold text-white mb-2">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
          </p>
          <p>
            IN NO EVENT SHALL {COMPANY.toUpperCase()}, ITS MEMBERS, MANAGERS, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, LICENSORS,
            OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES,
            INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE,
            SYSTEM FAILURE, THE COST OF SUBSTITUTE SERVICES, OR ANY OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH
            YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE SERVICE, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
            TORT INCLUDING NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE) AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF
            SUCH DAMAGES.
          </p>
          <p className="mt-3">
            IN NO EVENT SHALL {COMPANY.toUpperCase()}&apos;S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR
            RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS
            PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100.00).
          </p>
          <p className="mt-3">
            SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES; IN SUCH JURISDICTIONS, OUR LIABILITY
            SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
          </p>
        </Section>

        <Section title="7. Indemnification">
          <p>
            You agree to defend, indemnify, and hold harmless {COMPANY} and its members, managers, officers, employees, agents,
            licensors, and service providers from and against any claims, liabilities, damages, judgments, awards, losses, costs,
            expenses, or fees (including reasonable attorneys&apos; fees) arising out of or relating to your violation of these Terms
            or your use of the Service, including but not limited to any use of the Service&apos;s content or outputs other than as
            expressly authorized, or your violation of any third-party right.
          </p>
        </Section>

        <Section title="8. Third-Party Links and Services">
          <p>
            The Service may contain links to third-party websites, repositories, or resources. These links are provided for your
            convenience only. We have no control over the contents of those sites or resources and accept no responsibility for them
            or for any loss or damage that may arise from your use of them. Your access to and use of any third-party service is
            governed solely by the terms and policies of that third party.
          </p>
        </Section>

        <Section title="9. Governing Law and Dispute Resolution">
          <p>
            These Terms and any dispute or claim arising out of or related to them, their subject matter, or their formation
            (including non-contractual disputes or claims) shall be governed by and construed in accordance with the laws of
            the State of Delaware, without giving effect to any choice or conflict of law provision or rule.
          </p>
          <p className="mt-3">
            Any legal suit, action, or proceeding arising out of or relating to these Terms or the Service shall be instituted
            exclusively in the state or federal courts located in the State of Delaware. You irrevocably consent to personal
            jurisdiction and venue in those courts.
          </p>
          <p className="mt-3">
            You and {COMPANY} agree that any dispute resolution proceedings will be conducted only on an individual basis and
            not in a class, consolidated, or representative action.
          </p>
        </Section>

        <Section title="10. Modification of Terms">
          <p>
            We reserve the right to modify these Terms at any time at our sole discretion. We will indicate material changes by
            updating the &ldquo;Last Updated&rdquo; date at the top of this page and, where practicable, providing additional notice.
            Your continued use of the Service after the revised Terms become effective constitutes your acceptance of the changes.
            If you do not agree to the new Terms, you must stop using the Service.
          </p>
        </Section>

        <Section title="11. Severability and Waiver">
          <p>
            If any provision of these Terms is held invalid, illegal, or unenforceable by a court of competent jurisdiction, that
            provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall
            continue in full force and effect. Our failure to enforce any right or provision of these Terms shall not constitute
            a waiver of that right or provision unless acknowledged and agreed to by us in writing.
          </p>
        </Section>

        <Section title="12. Entire Agreement">
          <p>
            These Terms, together with our Privacy Policy and any other legal notices published by us on the Service, constitute
            the entire agreement between you and {COMPANY} concerning the Service and supersede all prior and contemporaneous
            agreements, proposals, representations, and understandings, whether written or oral, relating to the subject matter hereof.
          </p>
        </Section>

        <Section title="13. Contact Us">
          <p>
            Questions about these Terms should be directed to:
          </p>
          <div className="mt-3 text-white/70">
            <p className="font-semibold text-white">{COMPANY}</p>
            <p>Attn: Legal Department</p>
            <p>
              Email:{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#00FFC8] hover:underline">{CONTACT_EMAIL}</a>
            </p>
          </div>
        </Section>

        <div className="mt-16 pt-6 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-2">
          <p className="text-xs text-white/40">
            &copy; {new Date().getFullYear()} {COMPANY}. All rights reserved.
          </p>
          <div className="flex items-center gap-4 text-xs text-white/40">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-[#00FFC8]">Terms of Service</Link>
          </div>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-3 border-l-2 border-[#00FFC8] pl-3">{title}</h2>
      <div className="text-white/70 text-sm leading-relaxed space-y-2">{children}</div>
    </section>
  );
}
